DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS task;

CREATE TABLE user(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL
);

CREATE TABLE task(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER NOT NULL,
	title TEXT NOT NULL,
	time TIMESTAMP NOT NULL,
	priority TEXT NOT NULL CHECK(priority IN('Low','Medium','High')),
	FOREIGN KEY (user_id) REFERENCES user (id)
);
